### ISSUE TITLE
two way binding

### ISSUE THREAD

**Issue by robfletcher** [servergrove/NgSwitchery#5]
If I use `hg-model` on the checkbox toggling the switch updates the scope variable. Unfortunately the reverse is not the case. If I update the scope variable (and digest the scope) the hidden checkbox gets (un)checked but the switch does not change state.

**Comment by backwardgraphics** [comment]
So this doesn't fix the binding issue with Angular 1.3. Although the pull request referenced below will:
https://github.com/servergrove/NgSwitchery/pull/17

**Comment by Mr-Anonymous** [comment]
Is this fixed yet? I updated to the current version of Switchery downloaded today and I still have the same problem. In my form, the switchery is loaded with default value but later when the ng-model is changed from controller (due to other events), the switchery state doesnt change although the ng-model scope changes everywhere else.

**Comment by aramonc** [comment]
At this time I'm not sure when I will be able to update this project. Unfortunately it's no longer being used and it's very low priority. 

You may want to take a look at one of the forks or look at the README for a way to do the same with CSS.
